language: nix
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      script:
      - nix-build ./release.nix -I darwin=. -A examples.simple
      - nix-build ./release.nix -I darwin=. -A tests
    - os: osx
      osx_image: xcode7.3
      script:
      - nix-build ./release.nix -I darwin=. -A examples.simple
      - nix-build ./release.nix -I darwin=. -A tests
