language: nix
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      script: nix-build ./release.nix -A examples.simple
    - os: osx
      osx_image: xcode7.3
      script: nix-build ./release.nix -A examples.simple
